config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get "/pages/home", to: "pages#home"
  
  get "/signup", to: "chefs#new"
  resources :recipes do
    resources :comments, only: [:create]
  end
  resources :chefs, except: [:new]
  # resources :comments
  resources :ingredients, except: [:destroy]
  
  get     "/login",   to: "sessions#new"
  post    "/login",   to: "sessions#create"
  delete  "/logout",  to: "sessions#destroy"
  
  mount ActionCable.server => "/cable"
  
  get "/chat", to: "chatrooms#show"
  
  resources :messages, only: [:create]
  
  # # List all
  # get "/recipes", to: "recipes#index"
  
  # # Create new
  # # Must come before /recipes/:id or "new" will be considered as an id value
  # get "/recipes/new", to: "recipes#new" 
  
  # # show one
  # get "/recipes/:id", to: "recipes#show", as: "recipe"
  
  # # receive new form data and create one
  # post "/recipes", to: "recipes#create"
  
  # # Edit one
  # get "/recipes/:id/edit", to: "recipes#edit"
  
  # # receive edit form data and update one
  # patch "/recipes/:id", to: "recipes#update"
  
  # # Destroy one
  # delete "/recipes/:id", to: "recipes#destroy"

end

app/models/chef.rb
class Chef < ApplicationRecord
  before_save { self.email = email.downcase }
  
  validates :chefname, presence: true, length: {minimum: 2, maximum: 20}

  validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP } 
  
  validates :password, presence: true, length: {minimum: 5, maximum: 20}, allow_nil: true
  
  has_secure_password

  default_scope -> { order(lower(:chefname)) }
  
  has_many :recipes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :messages, dependent: :destroy

end

app/controllers/chefs_controller.rb
class ChefsController < ApplicationController
  
  before_action :set_chef, only: [:edit, :show, :update, :destroy]

  before_action :require_same_user, only: [:edit, :update, :destroy]
  
  before_action :require_admin, only: [:destroy]
  
  def index
    @chefs = Chef.paginate(page: params[:page], per_page: 2)
  end
  
  def new
    @chef = Chef.new
  end
  
  def show
    @chef_recipes = @chef.recipes.paginate(page: params[:page], per_page: 2)
  end
  
  def edit
  end
  
  def update
    if @chef.update(chef_params)
      flash[:success] = "Chef was updated successfully!"
      redirect_to @chef
    else
      render "edit"
    end
  end
  
  def create
    @chef = Chef.new(chef_params)
    if @chef.save
      session[:chef_if] = @chef.id
      cookies.signed[:chef_id] = @chef.id
      flash[:success] = "Welcome #{@chef.chefname} to MyRecipes App!"
      redirect_to @chef
    else
      render "new"
    end
  end
  
  def destroy
    if !@chef.admin?
      chefname = @chef.chefname
      if @chef.destroy
        flash[:danger] = "Chef '#{chefname}' was deleted, along with all associated recipes!"
        redirect_to chefs_path
      else
        render "show"
      end
    end
  end
  
  ############################################################################################
  
  private
    def chef_params
      params.require(:chef).permit(:chefname, :email, :password, :password_confirmation)
    end

    def set_chef
      @chef = Chef.find(params[:id])
    end

    def require_same_user
      if current_chef != @chef && !current_chef.admin
        flash[:danger] = "You can only edit or delete your own account!"
        redirect_to chefs_path
      end
    end
    
    def require_admin
      if logged_in? && !current_chef.admin?
        flash[:danger] = "Only administrators can perform that action!"
        redirect_to root_path
      end
    end
end

app/helpers/chefs_helper.rb
module ChefsHelper
end

app/views/chefs/_form.html.erb
<%= render "shared/errors", obj: @chef %>

<div class="row">
  <div class="col-md-12">
    <%= form_for(@chef, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      
      <div class="form-group">
        <div class="control-label col-md-2">
          <%= f.label :chefname, "Name" %>
        </div>
        <div class="col-md-8">
          <%= f.text_field :chefname, class: "form-control", placeholder: "Name of chef", autofocus: true %>
        </div>
      </div>
      
      <div class="form-group">
        <div class="control-label col-md-2">
          <%= f.label :email %>
        </div>
        <div class="col-md-8">
          <%= f.text_field :email, class: "form-control", placeholder: "Email address" %>
        </div>
      </div>
      
      <!--  Should hide these fields when updating -->
      
        <div class="form-group">
          <div class="control-label col-md-2">
            <%= f.label :password %>
          </div>
          <div class="col-md-8">
            <%= f.password_field :password, class: "form-control", placeholder: "Password" %>
          </div>
        </div>
      
        <div class="form-group">
          <div class="control-label col-md-2">
            <%= f.label :password_confirmation, "Confirm Password" %>
          </div>
          <div class="col-md-8">
            <%= f.password_field :password_confirmation, class: "form-control", placeholder: "Confirm Password" %>
          </div>
        </div>
        
      <!----------->
      
      <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
          <%= f.submit(@chef.new_record? ? "Create my account" : "Update my account", class: "btn btn-primary btn-lg btn-xlarge") %>
        </div>
      </div>
        
    <% end %>
    
    <div class="col-md-offset-4 col-md-4 colormatch">
      [ <%= link_to "Cancel request and return to recipes listing", recipes_path %> ]
    </div>
  </div>
</div>

app/views/chefs/edit.html.erb
<%= render "shared/page_title", title: @chef.chefname %> 

<%= render 'form' %>

app/views/chefs/index.html.erb
<%= render "shared/page_title", title: "Showing all chefs" %> 

<div align="center">
  <%= will_paginate %>
    <% @chefs.order("lower(chefname)").each do |chef| %>
      <ul class="listing">
        <div class="row">
          <div class="well col-md-offset-4 col-md-4">
            <li><%= link_to gravatar_for(chef), chef %></li>
            <li class="chef-title"><%= link_to chef.chefname, chef %></li>
            <li><small><%= pluralize(chef.recipes.count, "recipe") if chef.recipes.count > 0 %></small></li>
            <% if logged_in? && current_chef.admin? && !chef.admin? %>
              <li>
                <%= link_to "Delete this chef", 
                  chef_path(chef), 
                  method: :delete, 
                  data: { confirm: "Are you sure you want to delete the chef named '#{chef.chefname}'?"} %>
              </li>
            <% end %>
            <p>
              <span class="quiet"><small>Created 
              <%= time_ago_in_words(chef.created_at) %> ago</small></span>
            </p> 
          </div>
        </div>
      </ul>
    <% end %>
  <%= will_paginate %>
</div>

app/views/chefs/new.html.erb
<%= render "shared/page_title", title: "Sign up for the application" %> 

<%= render 'form' %>

app/views/chefs/show.html.erb
<%= render "shared/page_title", title: "#{@chef.chefname}'s Profile" %>

<% if @chef.admin? %>
  <h4 align="center" style="color: red; background: pink">Administrator</h4>
<% end %>

<div class="row">
  <div class="col-md-offset-4 col-md-4 center">
    <%= gravatar_for @chef, size: 150  %>
  </div>
</div>

<% if @chef.recipes.count > 0 %>
  <h4 align="center"><%= @chef.chefname %>'s recipes</h4>
  
  <div align="center">
    <%= will_paginate @chef_recipes %>
  </div>
  
  <%= render "recipes/recipe", obj: @chef_recipes %>
  
  <div align="center">
    <%= will_paginate @chef_recipes %>
  </div>
<% else %>
  <h4 align="center"><%= @chef.chefname %> has no recipes yet</h4>
<% end %>