config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get "/pages/home", to: "pages#home"
  
  get "/signup", to: "chefs#new"
  resources :recipes do
    resources :comments, only: [:create]
  end
  resources :chefs, except: [:new]
  # resources :comments
  resources :ingredients, except: [:destroy]
  
  get     "/login",   to: "sessions#new"
  post    "/login",   to: "sessions#create"
  delete  "/logout",  to: "sessions#destroy"
  
  mount ActionCable.server => "/cable"
  
  get "/chat", to: "chatrooms#show"
  
  resources :messages, only: [:create]
  
  # # List all
  # get "/recipes", to: "recipes#index"
  
  # # Create new
  # # Must come before /recipes/:id or "new" will be considered as an id value
  # get "/recipes/new", to: "recipes#new" 
  
  # # show one
  # get "/recipes/:id", to: "recipes#show", as: "recipe"
  
  # # receive new form data and create one
  # post "/recipes", to: "recipes#create"
  
  # # Edit one
  # get "/recipes/:id/edit", to: "recipes#edit"
  
  # # receive edit form data and update one
  # patch "/recipes/:id", to: "recipes#update"
  
  # # Destroy one
  # delete "/recipes/:id", to: "recipes#destroy"

end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  validates :name, presence: true, length: {minimum: 2, maximum: 25}, uniqueness: true
  
  default_scope -> { order(name: :asc) }
  
  has_many :recipe_ingredients
  has_many :recipes, through: :recipe_ingredients
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  
  before_action :set_ingredient, only: [:edit, :show, :update]
  
  before_action :require_admin, except: [:index, :show]
  
  def new
    @ingredient = Ingredient.new
  end
  
  def create
    @ingredient = Ingredient.new(ingredient_params)
    if @ingredient.save
      flash[:success] = "Ingredient was successfully created!"
      redirect_to @ingredient
    else
      render "new"
    end
  end
  
  def show
    @ingredient_recipes = @ingredient.recipes.paginate(page: params[:page], per_page: 2)
  end
  
  def index
    @ingredients = Ingredient.paginate(page: params[:page], per_page: 2)
  end
  
  def edit
  end
  
  def update
    if @ingredient.update(ingredient_params)
      flash[:success] = "Ingredient was updated successfully!"
      redirect_to @ingredient
    else
      render "edit"
    end
  end

  # def destroy
  # end

  private
    def ingredient_params
      params.require(:ingredient).permit(:name)
    end

    def set_ingredient
      @ingredient = Ingredient.find(params[:id])
    end

    def require_admin
      if !logged_in? || (logged_in? && !current_chef.admin?)
        flash[:danger] = "Only administrators can perform that action!"
        redirect_to ingredients_path
      end
    end
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/ingredients/_form.html.erb
<%= render "shared/errors", obj: @ingredient %>

<div class="row">
  <div class="col-md-12">
    <%= form_for(@ingredient, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      
      <div class="form-group">
        <div class="control-label col-md-2">
          <%= f.label :name, "Name" %>
        </div>
        <div class="col-md-8">
          <%= f.text_field :name, class: "form-control", placeholder: "Name of ingredient", autofocus: true %>
        </div>
      </div>
      
      <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
          <%= f.submit(@ingredient.new_record? ? "Create ingredient" : "Update ingredient", class: "btn btn-primary btn-lg btn-xlarge") %>
        </div>
      </div>
        
    <% end %>
    
    <div class="col-md-offset-4 col-md-4 colormatch">
      [ <%= link_to "Cancel request and return to ingredients listing", ingredients_path %> ]
    </div>
  </div>
</div>

app/views/ingredients/_ingredient.html.erb
<span class="badge"><%= link_to ingredient.name, ingredient %></span>

app/views/ingredients/edit.html.erb
<%= render "shared/page_title", title: @ingredient.name %> 

<%= render 'form' %>

app/views/ingredients/index.html.erb
<%= render "shared/page_title", title: "Listing all Ingredients" %> 

<div align="center">
  <%= will_paginate %>
    <% @ingredients.order("lower(name)").each do |ingredient| %>
      <ul class="listing">
        <div class="row">
          <div class="well col-md-offset-4 col-md-4">
            <li class="chef-title"><%= link_to ingredient.name, ingredient %></li>
            <li><small><%= pluralize(ingredient.recipes.count, "recipe") if ingredient.recipes.count > 0 %></small></li>
            <% if logged_in? && current_chef.admin? %>
              <li>
                <%= link_to "Edit this ingredient", edit_ingredient_path(ingredient) %>
              </li>
            <% end %>
            <p>
              <span class="quiet"><small>Created 
              <%= time_ago_in_words(ingredient.created_at) %> ago</small></span>
            </p> 
          </div>
        </div>
      </ul>
    <% end %>
  <%= will_paginate %>
</div>

app/views/ingredients/new.html.erb
<%= render "shared/page_title", title: "Create Ingredient" %> 

<%= render 'form' %>

app/views/ingredients/show.html.erb
<%= render "shared/page_title", title: "#{@ingredient.name}" %>

<% if @ingredient.recipes.count > 0 %>
  <h4 align="center"><%= @ingredient.name %> is in these recipes</h4>
  
  <div align="center">
    <%= will_paginate @ingredient_recipes %>
  </div>
  
  <%= render "recipes/recipe", obj: @ingredient_recipes %>
  
  <div align="center">
    <%= will_paginate @ingredient_recipes %>
  </div>
<% else %>
  <h4 align="center"><%= @ingredient.name %> has no recipes yet</h4>
<% end %>