config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get "/pages/home", to: "pages#home"
  
  get "/signup", to: "chefs#new"
  resources :recipes do
    resources :comments, only: [:create]
  end
  resources :chefs, except: [:new]
  # resources :comments
  resources :ingredients, except: [:destroy]
  
  get     "/login",   to: "sessions#new"
  post    "/login",   to: "sessions#create"
  delete  "/logout",  to: "sessions#destroy"
  
  mount ActionCable.server => "/cable"
  
  get "/chat", to: "chatrooms#show"
  
  resources :messages, only: [:create]
  
  # # List all
  # get "/recipes", to: "recipes#index"
  
  # # Create new
  # # Must come before /recipes/:id or "new" will be considered as an id value
  # get "/recipes/new", to: "recipes#new" 
  
  # # show one
  # get "/recipes/:id", to: "recipes#show", as: "recipe"
  
  # # receive new form data and create one
  # post "/recipes", to: "recipes#create"
  
  # # Edit one
  # get "/recipes/:id/edit", to: "recipes#edit"
  
  # # receive edit form data and update one
  # patch "/recipes/:id", to: "recipes#update"
  
  # # Destroy one
  # delete "/recipes/:id", to: "recipes#destroy"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chef.rb
class Chef < ApplicationRecord
  before_save { self.email = email.downcase }
  
  validates :chefname, presence: true, length: {minimum: 2, maximum: 20}

  validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP } 
  
  validates :password, presence: true, length: {minimum: 5, maximum: 20}, allow_nil: true
  
  has_secure_password

  default_scope -> { order(lower(:chefname)) }
  
  has_many :recipes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :messages, dependent: :destroy

end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :description, presence: true, length: {minimum: 10, maximum: 2000}
  
  validates :chef_id, presence: true
  validates :recipe_id, presence: true
  
  belongs_to :chef
  belongs_to :recipe
  
  default_scope -> { order(updated_at: :desc)}
  
end

app/models/cronreport.rb
class Cronreport < ApplicationRecord
  belongs_to :lookup
  has_many :cronreport_distributions
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  validates :name, presence: true, length: {minimum: 2, maximum: 25}, uniqueness: true
  
  default_scope -> { order(name: :asc) }
  
  has_many :recipe_ingredients
  has_many :recipes, through: :recipe_ingredients
end

app/models/lookup.rb
class Lookup < ApplicationRecord
  has_many :cronreports
end

app/models/message.rb
class Message < ApplicationRecord
  validates :content, presence: true#, length: {minimum: 10, maximum: 2000}
  
  validates :chef_id, presence: true

  belongs_to :chef

  def self.most_recent
    order(:created_at)#.last(3)
  end
  
end

app/models/recipe.rb
require 'csv'

class Recipe < ApplicationRecord
  validates :name,        presence: true, length: {minimum: 5, maximum: 100}
  
  validates :description, presence: true, length: {minimum: 10, maximum: 2000}
  
  validates :chef_id,     presence: true
  
  default_scope -> { order(updated_at: :desc) }
  
  belongs_to :chef
  
  has_many :recipe_ingredients
  has_many :ingredients, through: :recipe_ingredients
  has_many :comments, dependent: :destroy
  
  def chefname
    Chef.find(chef_id)
  end
  
  def self.to_csv
    CSV.generate(headers: true) do |csv|
      attributes = %w{ name description chefname }
      csv << attributes
      
      all.each do |recipe|
        # csv << recipe.attributes.values_at(*attributes)
        csv << attributes.map { |attr| recipe.send(attr) }
      end
    end
  end
end

app/models/recipe_ingredient.rb
class RecipeIngredient < ApplicationRecord
  validates :recipe_id, presence: true
  validates :ingredient_id, presence: true
  

  belongs_to :recipe
  belongs_to :ingredient
end

app/models/user.rb
class User < ApplicationRecord
  has_many :cronreport_distributions
end

app/controllers/chefs_controller.rb
class ChefsController < ApplicationController
  
  before_action :set_chef, only: [:edit, :show, :update, :destroy]

  before_action :require_same_user, only: [:edit, :update, :destroy]
  
  before_action :require_admin, only: [:destroy]
  
  def index
    @chefs = Chef.paginate(page: params[:page], per_page: 2)
  end
  
  def new
    @chef = Chef.new
  end
  
  def show
    @chef_recipes = @chef.recipes.paginate(page: params[:page], per_page: 2)
  end
  
  def edit
  end
  
  def update
    if @chef.update(chef_params)
      flash[:success] = "Chef was updated successfully!"
      redirect_to @chef
    else
      render "edit"
    end
  end
  
  def create
    @chef = Chef.new(chef_params)
    if @chef.save
      session[:chef_if] = @chef.id
      cookies.signed[:chef_id] = @chef.id
      flash[:success] = "Welcome #{@chef.chefname} to MyRecipes App!"
      redirect_to @chef
    else
      render "new"
    end
  end
  
  def destroy
    if !@chef.admin?
      chefname = @chef.chefname
      if @chef.destroy
        flash[:danger] = "Chef '#{chefname}' was deleted, along with all associated recipes!"
        redirect_to chefs_path
      else
        render "show"
      end
    end
  end
  
  ############################################################################################
  
  private
    def chef_params
      params.require(:chef).permit(:chefname, :email, :password, :password_confirmation)
    end

    def set_chef
      @chef = Chef.find(params[:id])
    end

    def require_same_user
      if current_chef != @chef && !current_chef.admin
        flash[:danger] = "You can only edit or delete your own account!"
        redirect_to chefs_path
      end
    end
    
    def require_admin
      if logged_in? && !current_chef.admin?
        flash[:danger] = "Only administrators can perform that action!"
        redirect_to root_path
      end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    redirect_to recipes_path if logged_in?
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  
  before_action :set_recipe, only: [:edit, :show, :update, :destroy]
  
  before_action :require_user, except: [:index, :show]

  before_action :require_same_user, only: [:edit, :update, :destroy]
  
  def index
    @recipes = Recipe.paginate(page: params[:page], per_page: 2)
    
    respond_to do |format|
      format.html
      format.csv { send_data @recipes.to_csv }
    end
  end
  
  def new
    @recipe = Recipe.new
  end
  
  def show
    @comment = Comment.new
    @comments = @recipe.comments.paginate(page: params[:page], per_page: 2)
  end
  
  def edit
  end
  
  def update
    if @recipe.update(recipe_params)
      flash[:success] = "Recipe was updated successfully!"
      redirect_to recipe_path(@recipe)
    else
      render "edit"
    end
  end
  
  def create
    @recipe = Recipe.new(recipe_params)
    
    @recipe.chef = current_chef
    
    if @recipe.save
      flash[:success] = "Recipe was created successfully!"
      redirect_to recipe_path(@recipe)
    else
      render "new"
    end
  end
  
  def destroy
    if @recipe.destroy
      flash[:success] = "Recipe was deleted!"
      redirect_to recipes_path
    else
      render "show"
    end
  end
  
  ############################################################################################
  
  private
    def recipe_params
      params.require(:recipe).permit(:name, :description, ingredient_ids: [])
    end

    def set_recipe
      @recipe = Recipe.find(params[:id])
    end
    
    def require_same_user
      if current_chef != @recipe.chef && !current_chef.admin?
        flash[:danger] = "You can only edit or delete your own recipes!"
        redirect_to recipes_path
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def gravatar_for(chef, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(chef.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: chef.chefname, class: "img-circle")
  end
  
end

app/helpers/chatrooms_helper.rb
module ChatroomsHelper
end

app/helpers/chefs_helper.rb
module ChefsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/_footer.html.erb
<nav class="navbar navbar-default">
  <div class="copyright-container">
    <div>© 2020 Copyright: <a href="https://kurtkrieger.com/">KurtKrieger.com</a></div>
    <div><a href="https://github.com/udemyrailscourse/tddror5railsudemy" target="_blank">Instructor's Repo</a>
      &nbsp;  <a href="https://github.com/kurtkrieger/myrecipes" target="_blank">Kurt's Repo</a></div>
  </div>
</nav>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-md-offset-1 col-md-10">
    <% flash.each do |type, msg| %>
      <div class="alert alert-<%= type %>">
        <a href="#" class="close" data-dismiss="alert">&#215;</a>
        <%= msg %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "MyRecipes", root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Chefs", chefs_path %></li>
        <li><%= link_to "All Recipes", recipes_path %></li>

        <% if logged_in? %>
          <li><%= link_to "Chef Chat", chat_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Recipes <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Create a new recipe", new_recipe_path %></li>
              <li><a href="#">Another action</a></li>
              <li><a href="#">Something else here</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Separated link</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">One more separated link</a></li>
            </ul>
          </li>
        <% end %>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" 
            aria-haspopup="true" aria-expanded="false">Ingredients<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "List all Ingredients", ingredients_path %></li>
            <% Ingredient.all.each do |ingredient| %>
              <li><%= link_to ingredient.name, ingredient%></li>
            <% end %>
            
            <% if logged_in? and current_chef.admin? %>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Create Ingredient", new_ingredient_path %></li>
            <% end %>
          </ul>
        </li>
        
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li class="dropdown">
            
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" 
                aria-haspopup="true" aria-expanded="false">
              <%= current_chef.chefname %>'s Profile <%= "(Admin)" if current_chef.admin? %>
              <span class="caret"></span>
            </a>
            
            <ul class="dropdown-menu">
              <li><%= link_to "View your profile", chef_path(current_chef) %></li>
              <li><%= link_to "Edit your profile", edit_chef_path(current_chef) %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Log out", logout_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myrecipes</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/navigation" %>
    
    <%= render "layouts/messages" %>
    
    admin@a.com/password
    
    <div class="container">
      <%= yield %>
    </div>
    
    <%= render "layouts/footer" %>
    
  </body>
</html>

app/views/pages/home.html.erb
<div class="jumbotron center">
  <h1>Welcome to MyRecipes App</h1>
  <h2>The best recipe sharing app!</h2>
  <p><%= link_to "Sign up for the app", signup_path, 
                                  class: "btn btn-danger btn-lg btn-xlarge" %></p>
</div>

<div class="row">
  <div class="col-lg-4">
    <h2>Heading</h2>
    <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
    <p><a class="btn btn-primary btn-xlarge" href="#" role="button">View details »</a></p>
  </div>
  <div class="col-lg-4">
    <h2>Heading</h2>
    <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
    <p><a class="btn btn-primary btn-xlarge" href="#" role="button">View details »</a></p>
 </div>
  <div class="col-lg-4">
    <h2>Heading</h2>
    <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa.</p>
    <p><a class="btn btn-primary btn-xlarge" href="#" role="button">View details »</a></p>
  </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row">
    <div class="col-md-offset-2 col-md-8">
      <div class="panel panel-danger">
        <div class="panel-heading">
          
          <h2 class="panel-title">
            <%= pluralize(obj.errors.count, "error") %> prevented saving this <%= obj.class %>:
          </h2>
          
          <div class="panel-body">
            <ul>
              <% obj.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
          
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_page_title.html.erb
<h1 align="center"><%= title %></h1>
<hr />